### ISSUE TITLE
Failed to render json schema dynamic form on nodejs-ex-chart.

### ISSUE THREAD

**Issue by akashshinde** [redhat-developer/redhat-helm-charts#19]
Dynamic form rendering is failing for following schema -https://github.com/redhat-developer/redhat-helm-charts/blob/master/alpha/nodejs-ex-k/values.schema.json

Tool used:  https://rjsf-team.github.io/react-jsonschema-form/

![image](https://user-images.githubusercontent.com/3337902/84785625-52e2a200-b009-11ea-9d13-72d8c60199c9.png)

**Comment by sbose78** [comment]
fixed
