### ISSUE TITLE
[regression] https://redhat-developer.github.io/redhat-helm-charts/index.yaml contains invalid references for charts

### ISSUE THREAD

**Issue by pmacik** [redhat-developer/redhat-helm-charts#61]
https://github.com/redhat-developer/redhat-helm-charts/pull/56 fixed this issue in the past but https://github.com/redhat-developer/redhat-helm-charts/pull/59 broke it again

**Comment by ldepandis** [comment]
I confirm it.
A customer notified me about this issue in his two OpenShift cluster, when he was trying to install a Helm Chart from the Red Hat Developer Catalog.
